import type { NextPage } from "next";
import Head from "next/head";
import { useActiveWeb3React } from "hooks/useActiveWeb3React";
import { useEffect } from "react";

const Home: NextPage = () => {
  const { account, chainId, error } = useActiveWeb3React();

  useEffect(() => {
    console.log(error);
  }, []);
  return (
    <div>
      <Head>
        <title>Create Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {account}---
        {chainId}
      </div>
    </div>
  );
};

export default Home;
